### ISSUE TITLE
js-controller 3.0.7 - errors

### ISSUE THREAD

**Issue by Ilovegym66** [Omega236/ioBroker.virtualpowermeter#32]
Hi, with js-controller 3.0.7, Node 12, NPM 6.14, Linux Buster, this error comes up:

`root@ioB-D10:/opt/iobroker/log# cat iobroker.2020-04-13.log | grep virtual
2020-04-13 10:38:47.932  - info: host.ioB-D10 stopInstance system.adapter.virtualpowermeter.0 (force=false, process=false)
2020-04-13 11:10:59.590  - info: host.ioB-D10 "system.adapter.virtualpowermeter.0" enabled
2020-04-13 11:10:59.644  - info: host.ioB-D10 instance system.adapter.virtualpowermeter.0 started with pid 8503
2020-04-13 11:11:05.957  - warn: virtualpowermeter.0 (8503) State value to set is invalid for yeelight-2.0.bslamp1-0x000000000f2c60fd.control.Virtual_Energy_Total: The state is missing the required property val!
2020-04-13 11:11:05.958  - warn: virtualpowermeter.0 (8503) This value will not be set in future versions. Please report this to the developer.
2020-04-13 11:11:05.958  - error: virtualpowermeter.0 (8503) uncaught exception: undefined is not a valid state value
2020-04-13 11:11:05.960  - error: virtualpowermeter.0 (8503) Error: undefined is not a valid state value
    at Virtualpowermeter.setUpdateTimestampEnergyTotal (/opt/iobroker/node_modules/iobroker.virtualpowermeter/main.js:203:16)
    at Virtualpowermeter.onStateChange (/opt/iobroker/node_modules/iobroker.virtualpowermeter/main.js:68:18)
2020-04-13 11:11:06.634  - info: host.ioB-D10 instance system.adapter.virtualpowermeter.0 terminated with code 0 (NO_ERROR)
2020-04-13 11:11:06.635  - info: host.ioB-D10 Restart adapter system.adapter.virtualpowermeter.0 because enabled
2020-04-13 11:11:26.551  - info: host.ioB-D10 "system.adapter.virtualpowermeter.0" disabled
2020-04-13 11:11:37.834  - error: virtualpowermeter.0 (8533) adapter disabled
2020-04-13 11:11:37.882  - warn: virtualpowermeter.0 (8533) Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
2020-04-13 11:11:38.421  - error: host.ioB-D10 instance system.adapter.virtualpowermeter.0 terminated with code 3 (NO_ADAPTER_CONFIG_FOUND)
2020-04-13 11:11:38.422  - info: host.ioB-D10 Do not restart adapter system.adapter.virtualpowermeter.0 because disabled or deleted
2020-04-13 11:20:14.041  - info: host.ioB-D10 iobroker upload virtualpowermeter
2020-04-13 11:20:15.006  - info: host.ioB-D10 iobroker upload [6] virtualpowermeter.admin /opt/iobroker/node_modules/iobroker.virtualpowermeter/admin/words.js words.js application/javascript
2020-04-13 11:20:15.103  - info: host.ioB-D10 iobroker upload [5] virtualpowermeter.admin /opt/iobroker/node_modules/iobroker.virtualpowermeter/admin/virtualpowermeter.png virtualpowermeter.png image/png
2020-04-13 11:20:15.190  - info: host.ioB-D10 iobroker upload [4] virtualpowermeter.admin /opt/iobroker/node_modules/iobroker.virtualpowermeter/admin/tsconfig.json tsconfig.json application/json
2020-04-13 11:20:15.284  - info: host.ioB-D10 iobroker upload [3] virtualpowermeter.admin /opt/iobroker/node_modules/iobroker.virtualpowermeter/admin/style.css style.css text/css
2020-04-13 11:20:15.343  - info: host.ioB-D10 iobroker upload [2] virtualpowermeter.admin /opt/iobroker/node_modules/iobroker.virtualpowermeter/admin/index_m.html index_m.html text/html
2020-04-13 11:20:15.401  - info: host.ioB-D10 iobroker upload [1] virtualpowermeter.admin /opt/iobroker/node_modules/iobroker.virtualpowermeter/admin/custom_m.html custom_m.html text/html
2020-04-13 11:20:15.471  - info: host.ioB-D10 iobroker upload [0] virtualpowermeter.admin /opt/iobroker/node_modules/iobroker.virtualpowermeter/admin/admin.d.ts admin.d.ts video/mp2t
2020-04-13 11:24:43.324  - info: host.ioB-D10 "system.adapter.virtualpowermeter.0" enabled
`

**Comment by Omega236** [comment]
Danke für den Report. 
Sei welches js-Controller Version besteht der Fehler?Ist der Fehler seit 3.0.x oder erst seit 3.0.7? Oder vielleicht sogar schon mit 2.x?
Mit welcher Version von virtualpowermeter passiert es? 

I

**Comment by Ilovegym66** [comment]
Hi, mit der 2.2.9 unter Node 10 und Linux Mint Debian Stretch funktioniert er einwandfrei.
Auf dem Testsystem hab ich ein frisch installiertes Debian Buster, Node 12, und leider erst mit 3.0.7 getestet.

**Comment by Omega236** [comment]
js-controller 3.0.7 läuft bei mir noch nicht unter Windows (installer gibts wohl auch noch nicht) daher mache ich erstmal nichts

**Comment by Ilovegym66** [comment]
Richtig 👍 eilt nicht.

**Comment by Apollon77** [comment]
Ist nur eine Warnung aktuell

**Comment by Apollon77** [comment]
Ooohhh no ... there is one warning ... but als "set undefined". Means: in  one of your setState commands you try to set "Undefined" as a value!

**Comment by Apollon77** [comment]
Ok, reason is for both cases https://github.com/Omega236/ioBroker.virtualpowermeter/blob/master/main.js#L203

you set a state without any value (which is undefined then). please set a proper value! in worst case use getState and setState but you need to set a value!

**Comment by Ilovegym66** [comment]
Hi, thank you for the fast support, well done! No faults any more.
